services:
  api:
    # image: gitmotion/ollama-api-server:latest
    build: .
    container_name: ollama-api
    ports:
      - "${PORT_EXTERNAL:-7777}:7777"
    environment:
      - PORT=7777
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
      - CORS_ORIGIN=*
      - API_KEYS=${API_KEYS:-default-key-1,default-key-2}